import {Typography} from "@mui/material";
import React from "react";

export default function LoremIpsum(props: { p: number }) {
    const text= "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ornare quam at diam tincidunt, ut bibendum nunc tempus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Maecenas ullamcorper, tellus vitae faucibus auctor, velit ante convallis lectus, id mattis quam enim vitae nunc. Praesent commodo dolor nulla. Fusce non pulvinar metus. Fusce rhoncus eleifend pulvinar. Morbi tempus dui nec nunc maximus faucibus. Cras ac lacus ultricies, porta tortor at, volutpat urna. Nunc gravida ligula eget mollis tempus.  Integer accumsan, eros sit amet dignissim tristique, tellus nulla mollis ex, eget pretium neque libero eu sem. Aliquam a lobortis tellus. Aliquam consequat massa sit amet diam posuere, quis pellentesque massa eleifend. Pellentesque ut purus lectus. Pellentesque ultrices at diam a iaculis. Curabitur in purus luctus, porttitor neque et, faucibus neque. Morbi massa nisi, pellentesque ut velit id, lobortis vulputate nulla. Curabitur eget magna ante.\n" +
        "\n" +
        "Curabitur bibendum, erat non ornare hendrerit, ipsum sapien pulvinar risus, sit amet iaculis sem mauris sed nibh. Curabitur ultrices rutrum nulla, vitae scelerisque sem tincidunt iaculis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin vitae ipsum at magna feugiat ornare in at libero. Donec in risus nibh. Nulla facilisi. Vestibulum tortor nibh, posuere in imperdiet sit amet, interdum id tellus. Integer nec arcu pretium, aliquet dui eu, ultricies nibh. Sed sed efficitur tellus. Suspendisse vitae malesuada est.\n" +
        "\n" +
        "Duis vitae nisl non diam euismod placerat mollis vitae nulla. Duis dictum risus at consequat blandit. Aliquam erat volutpat. Vestibulum pellentesque arcu tincidunt, tempus tellus at, vulputate odio. Donec nulla est, tincidunt nec felis in, fringilla condimentum augue. Curabitur at posuere quam. Donec at faucibus odio. Proin fermentum facilisis nibh a faucibus. Curabitur quis sagittis quam. Pellentesque cursus nec sapien non hendrerit. Phasellus aliquet dui at gravida egestas. Aenean feugiat a erat a imperdiet. Praesent vehicula ultrices purus, ut eleifend libero pharetra non.\n" +
        "\n" +
        "Aenean lobortis varius odio sit amet ultricies. Nunc eleifend consequat imperdiet. Vestibulum at lorem nulla. Pellentesque vitae pellentesque metus, et condimentum nibh. Integer quam mi, porta ac augue sed, finibus eleifend dui. Proin egestas est eu ipsum finibus dictum. Suspendisse eget sapien vel libero luctus porta. Mauris pretium, quam eu consectetur efficitur, arcu neque efficitur elit, sed elementum augue tellus at magna. Nulla laoreet, ipsum vitae luctus pretium, quam est tincidunt purus, porta aliquet nibh purus consectetur orci. Fusce ut congue neque. Maecenas eleifend sollicitudin sapien vitae mollis. Donec pellentesque porttitor enim. In hac habitasse platea dictumst. Proin consequat gravida erat ut porta. Nam sed lobortis lacus. ";
    return <Typography component="span">{text.replaceAll("\n", "").split('.').slice(0, props.p).join('.')}</Typography>;
}